swagger: '2.0'
info:
  description: "This is the backen documentation for custommindz"
  version: 1.0.0
  title: "Customindz"
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /dev
tags:
  - name: alert
    description: alert
  - name: configuration
    description: configuration
  - name: detection
    description: detection
schemes:
  - https
  - http
paths:
  /alert:
    post:
      tags:
        - alert
      summary: Add 
      description: ''
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '405':
          description: Invalid input
definitions:
  alert:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      engine:
        type: "string"
      interval:
        type: "string"
      output_type:
        type: "string"
      output_address:
        type: "string"
      trigger_record:
        type: "string"
      alert_type:
        type: "string"
  alert-log:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
  configuration:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      config:
        type: "string"
      monitor_id:
        type: "string"
      engine:
        type: "string"
  detection:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      timestamp:
        type: "string"
      alert:
        type: "string"
      result:
        type: "string"
      monitor_id:
        type: "string"
      engine:
        type: "string"
      image_url:
        type: "string"
  monitor:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      connection_uri:
        type: "string"
      play_from_source:
        type: "string"
      recording:
        type: "string"
      engines:
        type: "string"
      graph:
        type: "string"
  vod:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      flv_url:
        type: "string"
      thumbnail_url:
        type: "string"
      start_timestamp:
        type: "string"
      end_timestamp:
        type: "string"
        